name: nemethdaniel.com
favicon: null
layout_spectrum: 0.8978729292284697
typography_spectrum: 0.8040002987254411
title: nemethdaniel.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.10730725503526628
  lightness: 0.8366737209726125
  saturation: 0.18821305222809315
  rhythmicContrast: 0.5105186840519309
purpose: []
