name: Nemeth Daniel
favicon: null
layout_spectrum: 0.90728
typography_spectrum: 0.36812
title: nemethdaniel.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#070707'
    - '#34312c'
    - '#9c958f'
    - '#c1bcb9'
  brandStrength: 0.6875
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
