name: Nemeth Daniel
favicon: null
layout_spectrum: 0.91352
typography_spectrum: 0.53308
title: nemethdaniel.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#070707'
    - '#34312c'
    - '#9c958f'
    - '#c1bcb9'
  brandStrength: 0.125
  lightness: 0.8366737209726125
  saturation: 0.18821305222809315
  rhythmicContrast: 0.5105186840519309
purpose: []
