name: Nemeth Daniel
favicon: null
layout_spectrum: 0.90728
typography_spectrum: 0.36812
title: nemethdaniel.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#850d0e'
    - '#25ac14'
    - '#b3d318'
    - '#7d8f0f'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
